services:
  devhabit.api:
    image: ${DOCKER_REGISTRY-}devhabitapi
    build:
      context: .
      dockerfile: DevHabit.Api/Dockerfile
    ports:
    - 5000:8080
#    - 5001:8081
    environment:
       - ASPNETCORE_URLS=http://+:8080
      
      # Aspire Dashboard
       - OTEL_EXPORTER_OTLP_ENDPOINT=http://devhabit.aspire-dashboard:18889
       - OTEL_EXPORTER_OTLP_PROTOCOL=grpc

  devhabit.postgres:
    image: postgres:17.2 # or lates
    environment:
      POSTGRES_DB: devhabit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - devhabit_pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d devhabit" ]
      interval: 5s
      timeout: 5s
      retries: 10  
    
  devhabit.seq:
    image: datalust/seq:2024.3 # or latest
    environment:
      ACCEPT_EULA: "Y"
      SEQ_URLS: "http://0.0.0.0:80"
    volumes:
      - ./.containers/seq_data:/data
    ports:
      - 8080:80
      - 5341:5341

  devhabit.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888
  
volumes:
  devhabit_pgdata: